// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class Consultation
{
    public string Id { get; set; }

    public string AdjustedDesign { get; set; }

    public string AdjustedSpecification { get; set; }

    public string DesignId { get; set; }

    public string Note { get; set; }

    public virtual Design Design { get; set; }
}