// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class DesignTemplate
{
    public string Id { get; set; }

    public string DefaultLocation { get; set; }

    public string DefaultShape { get; set; }

    public string DefaultSize { get; set; }

    public string Description { get; set; }

    public string Image { get; set; }

    public string Name { get; set; }

    public decimal? TotalPrice { get; set; }

    public virtual ICollection<Design> Designs { get; set; } = new List<Design>();
}