// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class Feedback
{
    public string Id { get; set; }

    public string ProjectId { get; set; }

    public decimal Rating { get; set; }

    public string Content { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? UpdateDate { get; set; }

    public bool? IsDeleted { get; set; }

    public string CustomerId { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Project Project { get; set; }
}