// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class Invoice
{
    public string Id { get; set; }

    public decimal TotalAmout { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public DateTime PaymentDate { get; set; }

    public decimal TaxAmout { get; set; }

    public decimal DiscountApllied { get; set; }

    public string ProjectId { get; set; }

    public virtual Project Project { get; set; }
}