// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class Invoice
{
    public string Id { get; set; }

    public decimal? DiscountApplied { get; set; }

    public DateTime? PaymentDate { get; set; }

    public string PaymentMethod { get; set; }

    public string ProjectId { get; set; }

    public string Status { get; set; }

    public decimal? TaxAmount { get; set; }

    public decimal? TotalAmount { get; set; }

    public virtual Project Project { get; set; }
}