// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class Material
{
    public string Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public string Unit { get; set; }

    public int UnitPrice { get; set; }

    public string Description { get; set; }

    public string ProjectId { get; set; }

    public virtual Project Project { get; set; }
}