// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KPCOS.Data.Models;

public partial class PaymentPolicy
{
    public string Id { get; set; }

    public DateTime? CreateDate { get; set; }

    public string Description { get; set; }

    public string Name { get; set; }

    public int? PaymentDeadlineDay { get; set; }

    public string PaymentMethodAvailable { get; set; }

    public string RefundPolicy { get; set; }

    public DateTime? UpdateDate { get; set; }
}